[[apple.swift_library]]
name = "TuistConstants"
srcs = ["Sources/TuistConstants/Constants.swift"]
module_name = "TuistConstants"
minimum_os = "15.0"

[[apple.swift_library]]
name = "TuistThreadSafe"
srcs = ["Sources/TuistThreadSafe/LockedValue.swift"]
module_name = "TuistThreadSafe"
minimum_os = "15.0"

[[apple.swift_library]]
name = "TuistEnvironment"
srcs = ["Sources/TuistEnvironment/Environment.swift"]
deps = [
  "TuistConstants",
  "TuistThreadSafe",
]
module_name = "TuistEnvironment"
minimum_os = "15.0"

[[apple.swift_library]]
name = "TuistLogging"
srcs = ["Sources/TuistLogging/Logging.swift"]
deps = [
  "TuistConstants",
  "TuistEnvironment",
]
module_name = "TuistLogging"
minimum_os = "15.0"

[[apple.swift_library]]
name = "TuistServer"
srcs = ["Sources/TuistServer/Server.swift"]
deps = ["TuistLogging"]
module_name = "TuistServer"
minimum_os = "15.0"

[[apple.swift_library]]
name = "TuistKit"
srcs = ["Sources/TuistKit/Kit.swift"]
deps = [
  "TuistEnvironment",
  "TuistLogging",
  "TuistServer",
]
module_name = "TuistKit"
minimum_os = "15.0"

[[apple.macos_command_line_application]]
name = "tuist"
srcs = ["Sources/TuistCLI/main.swift"]
deps = [
  "TuistConstants",
  "TuistEnvironment",
  "TuistLogging",
  "TuistServer",
  "TuistKit",
]
module_name = "TuistCLI"
minimum_os = "15.0"
