use serde::Deserialize;

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum DependencyEcosystem {
    Rust,
    Swift,
    Go,
    Elixir,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DependencyEntry {
    pub package: String,
    pub name: String,
    pub ecosystem: DependencyEcosystem,
    pub manifest: String,
    pub lockfile: Option<String>,
    pub output: Option<String>,
}

pub const EXTERNAL_PACKAGE_CACHE_ROOT: &str = ".fabrik/external";
pub const EXTERNAL_TARGET_PREFIX: &str = "external:";

/// Format version of the build files `fabrik deps sync` generates under
/// [`EXTERNAL_PACKAGE_CACHE_ROOT`]. Bump this whenever the generated
/// `fabrik.toml` shape changes in a way that an older or newer Fabrik
/// would interpret differently. The loader refuses a generated file
/// stamped with a different version so a stale `.fabrik/external` tree
/// fails loudly instead of feeding a silently wrong graph into a build.
pub const GENERATED_EXTERNAL_FORMAT_VERSION: u32 = 1;

/// Marker that precedes the format version on the first line of a
/// generated external build file. Hand-authored external packages may
/// omit the stamp entirely; only a *mismatched* stamp is an error.
pub const GENERATED_EXTERNAL_FORMAT_MARKER: &str = "# fabrik:generated-external-format=";

/// The exact first line `fabrik deps sync` writes into a generated
/// external `fabrik.toml`.
#[must_use]
pub fn generated_external_format_header() -> String {
    format!("{GENERATED_EXTERNAL_FORMAT_MARKER}{GENERATED_EXTERNAL_FORMAT_VERSION}")
}

/// Read the generator-format stamp from a generated external build
/// file, if present. Returns `None` for hand-authored files that carry
/// no stamp (legacy and local/path packages stay loadable).
#[must_use]
pub fn parse_generated_external_format(src: &str) -> Option<u32> {
    src.lines().take(5).find_map(|line| {
        line.trim()
            .strip_prefix(GENERATED_EXTERNAL_FORMAT_MARKER)
            .and_then(|rest| rest.trim().parse().ok())
    })
}

pub fn external_dep_package(graph: &str) -> String {
    format!("{EXTERNAL_PACKAGE_CACHE_ROOT}/{graph}")
}

pub fn external_dep_id(graph: &str, name: &str) -> String {
    format!("{EXTERNAL_TARGET_PREFIX}{graph}/{name}")
}

pub fn external_target_id(external_package: &str, name: &str) -> String {
    format!("{EXTERNAL_TARGET_PREFIX}{external_package}/{name}")
}

pub(crate) fn into_entries(
    entries: Vec<DependencyEntryToml>,
    package: &str,
) -> Vec<DependencyEntry> {
    entries
        .into_iter()
        .map(|entry| DependencyEntry {
            package: package.to_string(),
            name: entry.name,
            ecosystem: entry.ecosystem,
            manifest: entry.manifest,
            lockfile: entry.lockfile,
            output: entry.output,
        })
        .collect()
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct DependencyEntryToml {
    name: String,
    ecosystem: DependencyEcosystem,
    manifest: String,
    lockfile: Option<String>,
    output: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_round_trips_through_the_parser() {
        let header = generated_external_format_header();
        let body = format!("{header}\n# Generated by `fabrik deps sync`.\n");
        assert_eq!(
            parse_generated_external_format(&body),
            Some(GENERATED_EXTERNAL_FORMAT_VERSION)
        );
    }

    #[test]
    fn missing_stamp_is_none_so_hand_authored_files_stay_loadable() {
        let body = "[[rust.library]]\nname = \"dep\"\n";
        assert_eq!(parse_generated_external_format(body), None);
    }

    #[test]
    fn a_different_version_is_reported_so_the_loader_can_reject_it() {
        let body = format!("{GENERATED_EXTERNAL_FORMAT_MARKER}999\n");
        assert_eq!(parse_generated_external_format(&body), Some(999));
    }

    #[test]
    fn stamp_is_only_honored_in_the_file_header() {
        // A marker buried deep in the file is ignored: the stamp is a
        // first-lines contract, not a free-floating sentinel.
        let body = format!(
            "[[rust.library]]\nname = \"a\"\n\n\n\n\n{GENERATED_EXTERNAL_FORMAT_MARKER}1\n"
        );
        assert_eq!(parse_generated_external_format(&body), None);
    }
}
