#!/usr/bin/env bash
#MISE description="Detect whether the current branch has releasable changes"
set -euo pipefail

latest_version="$(git tag -l | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1 || true)"

# git-cliff reads the repository's pull requests to render the notes, so a
# GitHub API failure has to stop the run. Swallowing it would leave the
# changelog empty, which reads as "nothing to release" and silently skips a
# release that was due.
if [[ -n "${latest_version}" ]]; then
  changelog="$(git cliff --config cliff.toml --repository . -- "${latest_version}..HEAD")"
else
  changelog="$(git cliff --config cliff.toml --repository .)"
fi

notes_section="$(printf '%s' "${changelog}" | sed -n '/<!-- RELEASE NOTES START -->/,/<!-- generated by git-cliff -->/p')"
should_release=false
if printf '%s' "${notes_section}" | grep -qE '^\*'; then
  should_release=true
fi

if [[ "${should_release}" == true ]]; then
  if [[ -n "${latest_version}" ]]; then
    next_version="$(git cliff --config cliff.toml --repository . --bumped-version -- "${latest_version}..HEAD")"
  else
    next_version="$(git cliff --config cliff.toml --repository . --bumped-version)"
  fi
else
  next_version="${latest_version:-0.1.0}"
fi

echo "latest-version=${latest_version:-none}"
echo "next-version=${next_version}"
echo "should-release=${should_release}"

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  {
    echo "latest-version=${latest_version}"
    echo "next-version=${next_version}"
    echo "should-release=${should_release}"
  } >> "${GITHUB_OUTPUT}"
fi
