[[target]]
name = "math"
kind = "zig_library"
srcs = ["src/**/*.zig"]

[target.attrs]
main = "src/math.zig"
import_name = "math"

[[target]]
name = "math_release"
kind = "zig_configure"
deps = ["./math"]

[target.attrs]
mode = "release_fast"
threaded = "single"
output = "static"
