[[deps]]
name = "rust_deps"
ecosystem = "rust"
manifest = "Cargo.toml"
lockfile = "Cargo.lock"
output = "__fabrik__/deps/rust_deps/fabrik.rust.lock.json"

[[cargo.binary]]
name = "fabrik"
cargo_package = "fabrik-cli"
bin = "fabrik"
srcs = [
  "Cargo.lock",
  "Cargo.toml",
]
src_globs = [
  "crates/*/Cargo.toml",
  "crates/*/src/**/*.rs",
]
