[[cargo.build_script]]
name = "build"
srcs = ["build.rs", "flag.txt"]

[[rust.library]]
name = "cfg-lib"
crate_name = "cfg_lib"
srcs = ["src/lib.rs"]
deps = ["//examples/rust/granular/build-script-cfg:build"]

[[rust.binary]]
name = "app"
srcs = ["src/main.rs"]
deps = ["//examples/rust/granular/build-script-cfg:cfg-lib"]
