apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "once.fullname" . }}
  labels:
    {{- include "once.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: 25m
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{ include "once.fullname" . }}-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "once.fullname" . }}
                port:
                  name: http
