[package]
name = "once-events-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
once-core.workspace = true

anyhow.workspace = true
prost = "0.14"
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-stream = "0.1"
tonic.workspace = true
tonic-prost = "0.14"
tracing.workspace = true
uuid.workspace = true

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = { version = "0.14", default-features = false }
tonic-prost-build = "0.14"

[lints]
workspace = true
