[[rust.library]]
name = "greeting"
srcs = ["src/lib.rs"]

[[rust.binary]]
name = "hello"
srcs = ["src/main.rs"]
deps = ["//examples/rust/granular/basic-app:greeting"]

[[rust.test]]
name = "greeting_test"
srcs = ["tests/greeting.rs"]
crate_root = "tests/greeting.rs"
deps = ["//examples/rust/granular/basic-app:greeting"]
