#shellcheck shell=bash
# Release script checks for SDK packaging and publishing validation.

Describe 'release SDK packaging scripts'
  BeforeEach 'setup_workspace'
  AfterEach 'cleanup_workspace'

  setup_release_path() {
    mkdir -p "$WORKSPACE/bin"
    PATH="$WORKSPACE/bin:$PATH"
    export PATH
  }

  write_stub() {
    path="$WORKSPACE/bin/$1"
    shift
    printf '%s\n' "$@" > "$path"
    chmod +x "$path"
  }

  setup_release_graph_workspace() {
    mkdir -p \
      "$WORKSPACE/crates/once-cas" \
      "$WORKSPACE/crates/once-core" \
      "$WORKSPACE/crates/once-frontend" \
      "$WORKSPACE/crates/once-host-tree" \
      "$WORKSPACE/crates/once" \
      "$WORKSPACE/crates/once-cli" \
      "$WORKSPACE/crates/once-events-client"
    touch \
      "$WORKSPACE/Cargo.toml" \
      "$WORKSPACE/once.toml" \
      "$WORKSPACE/crates/once-cas/once.toml" \
      "$WORKSPACE/crates/once-core/once.toml" \
      "$WORKSPACE/crates/once-frontend/once.toml" \
      "$WORKSPACE/crates/once-host-tree/once.toml" \
      "$WORKSPACE/crates/once/once.toml" \
      "$WORKSPACE/crates/once-cli/once.toml" \
      "$WORKSPACE/crates/once-events-client/once.toml"

    # The release manifest generator reads the locked versions of the
    # protobuf build dependencies so a dependency bump cannot silently
    # break the release build, and exits when it cannot find them. An
    # empty lock file is not a workspace it can generate for.
    cat > "$WORKSPACE/Cargo.lock" <<'LOCK'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "protoc-bin-vendored"
version = "3.2.0"

[[package]]
name = "tonic-build"
version = "0.14.6"

[[package]]
name = "tonic-prost-build"
version = "0.14.6"
LOCK
  }

  It 'copies a built shared library into each SDK prebuild directory'
    setup_release_path
    setup_release_graph_workspace
    write_stub cargo \
      '#!/usr/bin/env bash' \
      'case "$1" in' \
      '  vendor)' \
      '    mkdir -p third_party/rust/vendor' \
      '    ;;' \
      '  metadata)' \
      '    printf "%s\n" "{\"packages\":[]}"' \
      '    ;;' \
      'esac'
    write_stub mise \
      '#!/usr/bin/env bash' \
      'if [ "$1" = exec ] && [ "$2" = -- ]; then' \
      '  shift 2' \
      '  exec "$@"' \
      'fi' \
      'exit 2'
    write_stub jq \
      '#!/usr/bin/env bash'
    write_stub once \
      '#!/usr/bin/env bash' \
      'target_id="$2"' \
      'mkdir -p ".once/out/${target_id}"' \
      'printf library > ".once/out/${target_id}/libonce.so"'
    mkdir -p "$WORKSPACE/packages/js" "$WORKSPACE/packages/ruby"
    cd "$WORKSPACE"

    When call env ONCE_BIN="$WORKSPACE/bin/once" "$REPO_ROOT/mise/tasks/release/package-sdk-libs.sh" --target x86_64-unknown-linux-gnu
    The status should be success
    The contents of file "$WORKSPACE/packages/js/prebuilds/linux-x64/libonce.so" should equal 'library'
    The contents of file "$WORKSPACE/packages/ruby/prebuilds/linux-x64/libonce.so" should equal 'library'
  End

  It 'rejects unsupported SDK package targets'
    setup_release_path
    write_stub cargo \
      '#!/usr/bin/env bash' \
      'mkdir -p target/unknown-target/release' \
      'printf library > target/unknown-target/release/libonce.so'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/package-sdk-libs.sh" --target unknown-target
    The status should be failure
    The stderr should include 'unsupported SDK package target: unknown-target'
  End

  It 'rejects publish versions that are not semantic versions'
    setup_release_path
    write_stub gem '#!/usr/bin/env bash'
    write_stub npm '#!/usr/bin/env bash'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version latest
    The status should be failure
    The stderr should include '--version must be a semantic version'
  End

  It 'rejects publish versions with empty prerelease metadata'
    setup_release_path
    write_stub gem '#!/usr/bin/env bash'
    write_stub npm '#!/usr/bin/env bash'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 1.2.3-
    The status should be failure
    The stderr should include '--version must be a semantic version'
  End

  It 'rejects publish versions with empty build metadata'
    setup_release_path
    write_stub gem '#!/usr/bin/env bash'
    write_stub npm '#!/usr/bin/env bash'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 1.2.3+
    The status should be failure
    The stderr should include '--version must be a semantic version'
  End

  It 'rejects publish versions with malformed prerelease metadata'
    setup_release_path
    write_stub gem '#!/usr/bin/env bash'
    write_stub npm '#!/usr/bin/env bash'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 1.2.3-+foo
    The status should be failure
    The stderr should include '--version must be a semantic version'
  End

  It 'accepts publish versions with prerelease and build metadata'
    setup_release_path
    write_stub gem '#!/usr/bin/env bash'
    write_stub npm '#!/usr/bin/env bash'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 1.2.3-beta.1+build.5
    The status should be failure
    The stderr should include 'SDK prebuilds are missing'
  End

  It 'checks SDK prebuilds before publishing'
    setup_release_path
    write_stub gem '#!/usr/bin/env bash'
    write_stub npm '#!/usr/bin/env bash'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 0.1.0
    The status should be failure
    The stderr should include 'SDK prebuilds are missing'
  End

  # Staging a package tree that the publish path will actually walk, so the
  # registry stubs below are reached instead of the prebuilds guard.
  setup_publishable_packages() {
    mkdir -p \
      "$WORKSPACE/packages/js/prebuilds" \
      "$WORKSPACE/packages/ruby/prebuilds"
    printf '{"name":"buildonce","version":"0.0.0"}\n' > "$WORKSPACE/packages/js/package.json"
    printf 'Gem::Specification.new\n' > "$WORKSPACE/packages/ruby/once.gemspec"
  }

  It 'skips registries that already carry the version'
    setup_release_path
    setup_publishable_packages
    # `npm view <pkg>@<version>` succeeding is how npm reports that the
    # version is published; `gem list --remote` prints its own listing.
    write_stub npm \
      '#!/usr/bin/env bash' \
      'if [ "$1" = view ]; then exit 0; fi' \
      'echo "npm $* should not have run" >&2' \
      'exit 1'
    write_stub gem \
      '#!/usr/bin/env bash' \
      'if [ "$1" = list ]; then echo "buildonce (0.9.0, 0.1.0)"; exit 0; fi' \
      'echo "gem $* should not have run" >&2' \
      'exit 1'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 0.9.0
    The status should be success
    The stdout should include 'already on npm; skipping'
    The stdout should include 'already on RubyGems; skipping'
  End

  It 'matches published versions exactly rather than as substrings'
    setup_release_path
    setup_publishable_packages
    write_stub npm \
      '#!/usr/bin/env bash' \
      'if [ "$1" = --version ]; then echo 11.17.0; exit 0; fi' \
      'if [ "$1" = view ]; then exit 1; fi' \
      'exit 0'
    # 0.54.0 must not be read as published just because 0.5.4 is.
    write_stub gem \
      '#!/usr/bin/env bash' \
      'if [ "$1" = list ]; then echo "buildonce (0.5.4, 0.1.0)"; exit 0; fi' \
      'if [ "$1" = push ]; then echo "pushed $2"; exit 0; fi' \
      'exit 0'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 0.54.0
    The status should be success
    The stdout should not include 'already on RubyGems'
    The stdout should include 'pushed buildonce-0.54.0.gem'
  End

  It 'publishes to RubyGems even when npm publishing fails'
    setup_release_path
    setup_publishable_packages
    write_stub npm \
      '#!/usr/bin/env bash' \
      'if [ "$1" = --version ]; then echo 11.17.0; exit 0; fi' \
      'if [ "$1" = view ]; then exit 1; fi' \
      'if [ "$1" = publish ]; then echo "npm refused the credential" >&2; exit 1; fi' \
      'exit 0'
    write_stub gem \
      '#!/usr/bin/env bash' \
      'if [ "$1" = list ]; then echo "buildonce (0.1.0)"; exit 0; fi' \
      'if [ "$1" = push ]; then echo "pushed $2"; exit 0; fi' \
      'exit 0'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 0.9.0
    The status should be failure
    The stdout should include 'pushed buildonce-0.9.0.gem'
    The stderr should include 'failed to publish buildonce 0.9.0 to: npm'
  End

  It 'rejects npm clients too old for trusted publishing'
    setup_release_path
    setup_publishable_packages
    write_stub npm \
      '#!/usr/bin/env bash' \
      'if [ "$1" = view ]; then exit 1; fi' \
      'if [ "$1" = --version ]; then echo 10.9.2; exit 0; fi' \
      'exit 0'
    write_stub gem \
      '#!/usr/bin/env bash' \
      'if [ "$1" = list ]; then echo "buildonce (0.9.0)"; exit 0; fi' \
      'exit 0'
    cd "$WORKSPACE"

    When call "$REPO_ROOT/mise/tasks/release/publish-sdks.sh" --version 0.9.0
    The status should be failure
    The stdout should include 'already on RubyGems; skipping'
    The stderr should include 'npm 11.5.1 or newer is required to publish; found 10.9.2'
  End
End
