#shellcheck shell=bash
# End-to-end specs for `fabrik run` (target-style).

Describe 'fabrik run'
  BeforeEach 'setup_workspace'
  AfterEach 'cleanup_workspace'

  hello_workspace() {
    mkdir -p "$WORKSPACE/hello/src"
    cat > "$WORKSPACE/hello/src/main.rs" <<'EOF'
fn main() {
    println!("hello fabrik");
}
EOF
    cat > "$WORKSPACE/hello/fabrik.toml" <<'EOF'
[[rust.binary]]
name = "hello"
src_globs = ["src/*.rs"]
EOF
  }

  It 'runs a rust_binary target and writes the binary under .fabrik/out'
    hello_workspace
    When call fabrik run hello/hello
    The status should be success
    The stderr should include 'cache miss'
    The stderr should include 'exit=0'
    The path "$WORKSPACE/.fabrik/out/hello/hello" should be exist
  End

  It 'produces a runnable binary'
    hello_workspace
    fabrik run hello/hello >/dev/null 2>&1
    When call "$WORKSPACE/.fabrik/out/hello/hello"
    The status should be success
    The stdout should equal 'hello fabrik'
  End

  It 'is a cache hit on a second invocation'
    hello_workspace
    fabrik run hello/hello >/dev/null 2>&1
    When call fabrik run hello/hello
    The status should be success
    The stderr should include 'cache hit'
  End

  It 'invalidates a rust_binary target when a source changes'
    hello_workspace
    fabrik run hello/hello >/dev/null 2>&1
    cat > "$WORKSPACE/hello/src/main.rs" <<'EOF'
fn main() {
    println!("hello again");
}
EOF
    When call fabrik run hello/hello
    The status should be success
    The stderr should include 'cache miss'
  End

  It 'runs a cargo_binary target'
    mkdir -p "$WORKSPACE/src"
    cat > "$WORKSPACE/src/main.rs" <<'EOF'
fn main() {
    println!("cargo app");
}
EOF
    cat > "$WORKSPACE/Cargo.toml" <<'EOF'
[package]
name = "app"
version = "0.0.0"
edition = "2021"
EOF
    cat > "$WORKSPACE/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app"
version = "0.0.0"
EOF
    cat > "$WORKSPACE/fabrik.toml" <<'EOF'
[[cargo.binary]]
name = "app"
cargo_package = "app"
srcs = ["Cargo.lock", "Cargo.toml", "src/main.rs"]
EOF
    When call fabrik run app
    The status should be success
    The stderr should include 'cache miss'
    The path "$WORKSPACE/target/debug/app" should be exist
  End

  It 'runs a manifest-backed script target declared in fabrik.toml'
    mkdir -p "$WORKSPACE/scripts"
    cat > "$WORKSPACE/scripts/input.txt" <<'EOF'
hello inline script
EOF
    cat > "$WORKSPACE/scripts/fabrik.toml" <<'EOF'
[[target]]
name = "print"
rule = "script"

[target.script]
argv = ["/bin/sh", "-c", "cat input.txt"]
input = ["input.txt"]
cwd = "scripts"
EOF
    When call fabrik run scripts/print
    The status should be success
    The stdout should equal 'hello inline script'
    The stderr should include 'cache miss'
  End

  It 'runs a script target and restores its declared output'
    mkdir -p "$WORKSPACE/scripts/scripts"
    cat > "$WORKSPACE/scripts/scripts/build.sh" <<'EOF'
#!/bin/sh
# FABRIK input "../input.txt"
# FABRIK output "../out.txt"
# FABRIK cwd ".."
printf '%s' "$(cat input.txt)" > out.txt
printf '%s' "$(cat out.txt)"
EOF
    chmod +x "$WORKSPACE/scripts/scripts/build.sh"
    cat > "$WORKSPACE/scripts/input.txt" <<'EOF'
hello script
EOF
    cat > "$WORKSPACE/scripts/fabrik.toml" <<'EOF'
[[target]]
name = "build"
rule = "script"

[target.script]
path = "scripts/build.sh"
EOF
    When call fabrik run scripts/build
    The status should be success
    The stdout should equal 'hello script'
    The stderr should include 'cache miss'
    The contents of file "$WORKSPACE/scripts/out.txt" should equal 'hello script'
  End

  It 'reuses the cache for a script target'
    mkdir -p "$WORKSPACE/scripts/scripts"
    cat > "$WORKSPACE/scripts/scripts/build.sh" <<'EOF'
#!/bin/sh
# FABRIK input "../input.txt"
# FABRIK output "../out.txt"
# FABRIK cwd ".."
printf '%s' "$(cat input.txt)" > out.txt
printf '%s' "$(cat out.txt)"
EOF
    chmod +x "$WORKSPACE/scripts/scripts/build.sh"
    cat > "$WORKSPACE/scripts/input.txt" <<'EOF'
cached script
EOF
    cat > "$WORKSPACE/scripts/fabrik.toml" <<'EOF'
[[target]]
name = "build"
rule = "script"

[target.script]
path = "scripts/build.sh"
EOF
    fabrik run scripts/build >/dev/null 2>&1
    When call fabrik run scripts/build
    The status should be success
    The stdout should equal 'cached script'
    The stderr should include 'cache hit'
  End

  It 'runs a script target through the microsandbox compute provider'
    mkdir -p "$WORKSPACE/bin" "$WORKSPACE/scripts"
    cat > "$WORKSPACE/bin/microsandbox" <<'EOF'
#!/bin/sh
test "$1" = "run" || exit 64
shift
workspace=""
cwd=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --workspace)
      shift
      workspace="$1"
      ;;
    --cwd)
      shift
      cwd="$1"
      ;;
    --)
      shift
      break
      ;;
  esac
  shift
done
printf 'provider stderr\n' >&2
cd "$workspace/${cwd:-.}" || exit 1
exec "$@"
EOF
    chmod +x "$WORKSPACE/bin/microsandbox"
    cat > "$WORKSPACE/scripts/fabrik.toml" <<'EOF'
[[target]]
name = "remote"
rule = "script"

[target.script]
argv = ["/bin/sh", "-c", "printf remote-output"]
remote = "microsandbox"
EOF
    When call env PATH="$WORKSPACE/bin:/usr/bin:/bin" "$FABRIK_BIN" -C "$WORKSPACE" run scripts/remote
    The status should be success
    The stdout should equal 'remote-output'
    The stderr should include 'provider stderr'
    The stderr should include 'cache miss'
  End

  It 'runs a script target through the daytona compute provider'
    mkdir -p "$WORKSPACE/bin" "$WORKSPACE/scripts"
    cat > "$WORKSPACE/bin/daytona" <<'EOF'
#!/bin/sh
test "$1" = "exec" || exit 64
shift
sandbox="$1"
shift
cwd=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    --cwd)
      shift
      cwd="$1"
      ;;
    --timeout)
      shift
      ;;
    --)
      shift
      break
      ;;
  esac
  shift
done
test "$sandbox" = "sandbox-1" || exit 65
printf 'daytona provider stderr\n' >&2
cd "$cwd" || exit 1
exec "$@"
EOF
    chmod +x "$WORKSPACE/bin/daytona"
    cat > "$WORKSPACE/scripts/fabrik.toml" <<'EOF'
[[target]]
name = "daytona"
rule = "script"

[target.script]
argv = ["/bin/sh", "-c", "printf daytona-target"]
remote = "daytona"
EOF
    When call env PATH="$WORKSPACE/bin:/usr/bin:/bin" FABRIK_DAYTONA_SANDBOX=sandbox-1 FABRIK_DAYTONA_WORKDIR="$WORKSPACE" "$FABRIK_BIN" -C "$WORKSPACE" run scripts/daytona
    The status should be success
    The stdout should equal 'daytona-target'
    The stderr should include 'daytona provider stderr'
    The stderr should include 'cache miss'
  End

  It 'runs a runtime script target and emits its runtime interfaces'
    mkdir -p "$WORKSPACE/tasks"
    cat > "$WORKSPACE/tasks/fabrik.toml" <<'EOF'
[[target]]
name = "launch"
rule = "script"

[target.script]
argv = ["/bin/sh", "-c", "printf launched"]

[target.runtime]
kind = "ios_simulator"
capabilities = ["logs", "ui_tree", "ui_action"]

[[target.runtime.interface]]
name = "logs"
kind = "stream"
argv = ["xcrun", "simctl", "spawn", "booted", "log", "stream"]
description = "Stream simulator logs"
EOF
    When call "$FABRIK_BIN" --format json -C "$WORKSPACE" run tasks/launch
    The status should be success
    The stdout should include '"kind":"runtime_script"'
    The stdout should include '"runtime":{"kind":"ios_simulator"'
    The stdout should include '"capabilities":["logs","ui_tree","ui_action"]'
    The stdout should include '"name":"logs"'
    The stdout should include '"argv":["xcrun","simctl","spawn","booted","log","stream"]'
  End

  It 'builds and launches an apple_simulator_app target'
    mkdir -p "$WORKSPACE/bin" "$WORKSPACE/App/Sources"
    cat > "$WORKSPACE/bin/xcrun" <<'EOF'
#!/bin/sh
if [ "$1" = "--sdk" ] && [ "$3" = "--show-sdk-path" ]; then
  echo "/tmp/fake-iphonesimulator.sdk"
  exit 0
fi
if [ "$1" = "--sdk" ] && [ "$3" = "swiftc" ]; then
  shift 3
  exec swiftc "$@"
fi
if [ "$1" = "simctl" ]; then
  echo "$*" >> simctl.log
  exit 0
fi
echo "unexpected xcrun invocation: $*" >&2
exit 2
EOF
    cat > "$WORKSPACE/bin/swiftc" <<'EOF'
#!/bin/sh
out=""
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    shift
    out="$1"
  fi
  shift
done
mkdir -p "$(dirname "$out")"
printf 'fake app binary' > "$out"
EOF
    cat > "$WORKSPACE/bin/codesign" <<'EOF'
#!/bin/sh
for last do :; done
app="$last"
mkdir -p "$app/_CodeSignature"
printf 'signed' > "$app/_CodeSignature/CodeResources"
EOF
    chmod +x "$WORKSPACE/bin/xcrun" "$WORKSPACE/bin/swiftc" "$WORKSPACE/bin/codesign"
    cat > "$WORKSPACE/App/Sources/App.swift" <<'EOF'
import SwiftUI

@main
struct DemoApp: App {
    var body: some Scene {
        WindowGroup { Text("Hello") }
    }
}
EOF
    cat > "$WORKSPACE/App/fabrik.toml" <<'EOF'
[[apple.simulator_app]]
name = "Demo"
platform = "ios"
bundle_id = "dev.fabrik.demo"
srcs = ["Sources/App.swift"]
minimum_os = "17.0"
EOF
    When call env PATH="$WORKSPACE/bin:$PATH" "$FABRIK_BIN" -C "$WORKSPACE" run App/Demo
    The status should be success
    The stderr should include 'cache miss'
    The contents of file "$WORKSPACE/simctl.log" should include 'simctl install booted'
    The contents of file "$WORKSPACE/simctl.log" should include 'simctl launch booted dev.fabrik.demo'
  End

  It 'emits simulator runtime interfaces for an apple_simulator_app target'
    mkdir -p "$WORKSPACE/bin" "$WORKSPACE/App/Sources"
    cat > "$WORKSPACE/bin/xcrun" <<'EOF'
#!/bin/sh
if [ "$1" = "--sdk" ] && [ "$3" = "--show-sdk-path" ]; then
  echo "/tmp/fake-iphonesimulator.sdk"
  exit 0
fi
if [ "$1" = "--sdk" ] && [ "$3" = "swiftc" ]; then
  shift 3
  exec swiftc "$@"
fi
if [ "$1" = "simctl" ]; then
  exit 0
fi
exit 2
EOF
    cat > "$WORKSPACE/bin/swiftc" <<'EOF'
#!/bin/sh
out=""
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    shift
    out="$1"
  fi
  shift
done
mkdir -p "$(dirname "$out")"
printf 'fake app binary' > "$out"
EOF
    cat > "$WORKSPACE/bin/codesign" <<'EOF'
#!/bin/sh
for last do :; done
app="$last"
mkdir -p "$app/_CodeSignature"
printf 'signed' > "$app/_CodeSignature/CodeResources"
EOF
    chmod +x "$WORKSPACE/bin/xcrun" "$WORKSPACE/bin/swiftc" "$WORKSPACE/bin/codesign"
    cat > "$WORKSPACE/App/Sources/App.swift" <<'EOF'
import SwiftUI

@main
struct DemoApp: App {
    var body: some Scene {
        WindowGroup { Text("Hello") }
    }
}
EOF
    cat > "$WORKSPACE/App/fabrik.toml" <<'EOF'
[[apple.simulator_app]]
name = "Demo"
platform = "ios"
bundle_id = "dev.fabrik.demo"
srcs = ["Sources/App.swift"]
minimum_os = "17.0"
EOF
    When call env PATH="$WORKSPACE/bin:$PATH" "$FABRIK_BIN" --format json -C "$WORKSPACE" run App/Demo
    The status should be success
    The stdout should include '"runtime":{"kind":"ios_simulator"'
    The stdout should include '"capabilities":["logs","screenshot","ui_tree","ui_action"]'
    The stdout should include '"name":"ui_tree"'
    The stdout should include '"name":"tap"'
  End

  It 'errors when the target id does not match any target'
    hello_workspace
    When call fabrik run hello/nope
    The status should not equal 0
    The stderr should include 'no target matches'
  End

  It 'errors on an unsupported target kind'
    mkdir -p "$WORKSPACE/lib"
    : > "$WORKSPACE/lib/lib.rs"
    cat > "$WORKSPACE/lib/fabrik.toml" <<'EOF'
[[rust.library]]
name = "lib"
srcs = ["lib.rs"]
EOF
    When call fabrik run lib/lib
    The status should not equal 0
    The stderr should include 'rust_library'
  End

  It 'emits a JSON outcome record on stdout under --format json'
    hello_workspace
    When call "$FABRIK_BIN" --format json -C "$WORKSPACE" run hello/hello
    The status should be success
    The stdout should include '"target":"hello/hello"'
    The stdout should include '"cache":"miss"'
    The stdout should include '"exit_code":0'
    The stdout should include '"output":".fabrik/out/hello/hello"'
    The stdout should include '"action_digest":'
  End

  It 'emits a TOON outcome record on stdout under --format toon'
    hello_workspace
    When call "$FABRIK_BIN" --format toon -C "$WORKSPACE" run hello/hello
    The status should be success
    The stdout should include 'target: hello/hello'
    The stdout should include 'cache: miss'
    The stdout should include 'exit_code: 0'
    The stdout should include 'output: .fabrik/out/hello/hello'
    The stdout should include 'action_digest:'
  End
End
