#shellcheck shell=bash
# End-to-end specs for `fabrik run` (target-style).

Describe 'fabrik run'
  BeforeEach 'setup_workspace'
  AfterEach 'cleanup_workspace'

  hello_workspace() {
    mkdir -p "$WORKSPACE/hello/src"
    cat > "$WORKSPACE/hello/src/main.rs" <<'EOF'
fn main() {
    println!("hello fabrik");
}
EOF
    cat > "$WORKSPACE/hello/fabrik.star" <<'EOF'
rust_binary(name = "hello", srcs = glob(["src/*.rs"]))
EOF
  }

  It 'runs a rust_binary target and writes the binary under .fabrik/out'
    hello_workspace
    When call fabrik run //hello:hello
    The status should be success
    The stderr should include 'cache miss'
    The stderr should include 'exit=0'
    The path "$WORKSPACE/.fabrik/out/hello/hello" should be exist
  End

  It 'produces a runnable binary'
    hello_workspace
    fabrik run //hello:hello >/dev/null 2>&1
    When call "$WORKSPACE/.fabrik/out/hello/hello"
    The status should be success
    The stdout should equal 'hello fabrik'
  End

  It 'is a cache hit on a second invocation'
    hello_workspace
    fabrik run //hello:hello >/dev/null 2>&1
    When call fabrik run //hello:hello
    The status should be success
    The stderr should include 'cache hit'
  End

  It 'invalidates a rust_binary target when a source changes'
    hello_workspace
    fabrik run //hello:hello >/dev/null 2>&1
    cat > "$WORKSPACE/hello/src/main.rs" <<'EOF'
fn main() {
    println!("hello again");
}
EOF
    When call fabrik run //hello:hello
    The status should be success
    The stderr should include 'cache miss'
  End

  It 'runs a cargo_binary target'
    mkdir -p "$WORKSPACE/src"
    cat > "$WORKSPACE/src/main.rs" <<'EOF'
fn main() {
    println!("cargo app");
}
EOF
    cat > "$WORKSPACE/Cargo.toml" <<'EOF'
[package]
name = "app"
version = "0.0.0"
edition = "2021"
EOF
    cat > "$WORKSPACE/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app"
version = "0.0.0"
EOF
    cat > "$WORKSPACE/fabrik.star" <<'EOF'
cargo_binary(
    name = "app",
    cargo_package = "app",
    srcs = ["Cargo.lock", "Cargo.toml", "src/main.rs"],
)
EOF
    When call fabrik run //:app
    The status should be success
    The stderr should include 'cache miss'
    The path "$WORKSPACE/target/debug/app" should be exist
  End

  It 'passes mise trust variables to cargo_binary actions'
    mkdir -p "$WORKSPACE/bin" "$WORKSPACE/src"
    cat > "$WORKSPACE/bin/cargo" <<EOF
#!/bin/sh
if [ "\$MISE_TRUSTED_CONFIG_PATHS" != "$WORKSPACE" ]; then
  echo "missing mise trust path" >&2
  exit 42
fi
if [ "\$MISE_YES" != "1" ]; then
  echo "missing mise yes" >&2
  exit 43
fi
EOF
    chmod +x "$WORKSPACE/bin/cargo"
    cat > "$WORKSPACE/src/main.rs" <<'EOF'
fn main() {}
EOF
    cat > "$WORKSPACE/Cargo.toml" <<'EOF'
[package]
name = "app"
version = "0.0.0"
edition = "2021"
EOF
    cat > "$WORKSPACE/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "app"
version = "0.0.0"
EOF
    cat > "$WORKSPACE/fabrik.star" <<'EOF'
cargo_binary(
    name = "app",
    cargo_package = "app",
    srcs = ["Cargo.lock", "Cargo.toml", "src/main.rs"],
)
EOF
    When call env PATH="$WORKSPACE/bin:$PATH" MISE_TRUSTED_CONFIG_PATHS="$WORKSPACE" MISE_YES=1 "$FABRIK_BIN" -C "$WORKSPACE" run //:app
    The status should be success
    The stderr should include 'cache miss'
  End

  It 'errors when the label does not match any target'
    hello_workspace
    When call fabrik run //hello:nope
    The status should not equal 0
    The stderr should include 'no target matches'
  End

  It 'errors on an unsupported target kind'
    mkdir -p "$WORKSPACE/lib"
    : > "$WORKSPACE/lib/lib.rs"
    cat > "$WORKSPACE/lib/fabrik.star" <<'EOF'
rust_library(name = "lib", srcs = ["lib.rs"])
EOF
    When call fabrik run //lib:lib
    The status should not equal 0
    The stderr should include 'rust_library'
  End

  It 'emits a JSON outcome record on stdout under --format json'
    hello_workspace
    When call "$FABRIK_BIN" --format json -C "$WORKSPACE" run //hello:hello
    The status should be success
    The stdout should include '"label":"//hello:hello"'
    The stdout should include '"cache":"miss"'
    The stdout should include '"exit_code":0'
    The stdout should include '"output":".fabrik/out/hello/hello"'
    The stdout should include '"action_digest":'
  End

  It 'emits a TOON outcome record on stdout under --format toon'
    hello_workspace
    When call "$FABRIK_BIN" --format toon -C "$WORKSPACE" run //hello:hello
    The status should be success
    The stdout should include 'label: //hello:hello'
    The stdout should include 'cache: miss'
    The stdout should include 'exit_code: 0'
    The stdout should include 'output: .fabrik/out/hello/hello'
    The stdout should include 'action_digest:'
  End
End
