PRELUDE_SOURCES = [
    "common.star",
    "archive.star",
    "lint.star",
    "apple.star",
    "android.star",
    "go.star",
    "rust.star",
    "xcode.star",
    "swift_package.star",
    "c.star",
    "cmake.star",
    "zig.star",
    "swift.star",
    "kotlin.star",
    "elixir.star",
    "python.star",
    "ruby.star",
    "javascript.star",
    "react_native.star",
    "oci.star",
    "dockerfile.star",
    "bazel.star",
]

PRELUDE_DEPENDENCIES = {
    "xcode.star": ["apple.star", "archive.star"],
    "react_native.star": ["android.star"],
    "swift_package.star": ["apple.star", "xcode.star"],
}

PRELUDE_TARGET_KINDS = {
    "archive.star": ["archive_download"],
    "lint.star": [
        "ruff_lint",
        "golangci_lint",
        "swiftlint_lint",
        "detekt_lint",
        "credo_lint",
        "eslint_lint",
        "rubocop_lint",
    ],
    "android.star": [
        "android_resource",
        "android_library",
        "android_local_test",
        "android_instrumentation_test",
        "android_binary",
    ],
    "apple.star": [
        "swift_macro",
        "swift_package_dependencies",
        "swift_package_pin",
        "apple_library",
        "apple_system_module",
        "apple_resource_bundle",
        "apple_xcframework_import",
        "apple_framework",
        "apple_application",
        "apple_thinned_package",
        "apple_test_bundle",
        "shellspec_test",
    ],
    "swift_package.star": ["swift_package_workspace"],
    "go.star": [
        "go_dependencies",
        "go_module",
        "go_source",
        "go_library",
        "go_binary",
        "go_test",
    ],
    "rust.star": [
        "cargo_workspace",
        "cargo_dependencies",
        "rust_library",
        "rust_mobile_library",
        "rust_binary",
        "rust_test",
        "rust_crate",
        "rust_proc_macro",
    ],
    "xcode.star": [
        "xcode_workspace",
    ],
    "c.star": ["c_library"],
    "cmake.star": [
        "cmake_project",
        "cmake_workspace",
        "cmake_target",
    ],
    "zig.star": [
        "zig_dependencies",
        "zig_package",
        "zig_library",
        "zig_c_library",
        "zig_binary",
        "zig_static_library",
        "zig_shared_library",
        "zig_configure",
        "zig_configure_binary",
        "zig_test",
        "zig_configure_test",
    ],
    "swift.star": ["swift_android_library"],
    "kotlin.star": [
        "kotlin_apple_framework",
        "kotlin_jvm_library",
        "kotlin_jvm_binary",
        "kotlin_jvm_test",
    ],
    "elixir.star": [
        "mix_workspace",
        "mix_dependencies",
        "mix_package",
        "mix_project",
        "mix_release",
        "elixir_library",
        "elixir_test",
    ],
    "python.star": ["pytest_test"],
    "ruby.star": [
        "rspec_test",
        "minitest_test",
    ],
    "javascript.star": [
        "vitest_test",
        "jest_test",
    ],
    "react_native.star": [
        "react_native_dependencies",
        "react_native_module",
        "react_native_bundle",
        "react_native_codegen",
        "react_native_autolinking",
        "react_native_apple_application",
        "react_native_android_application",
        "react_native_metro",
    ],
    "oci.star": [
        "oci_layer",
        "oci_image",
    ],
    "dockerfile.star": [
        "dockerfile_image",
    ],
    "bazel.star": [
        "bazel_workspace",
        "bazel_target",
    ],
}
