PRELUDE_SOURCES = [
    "common.star",
    "apple.star",
    "android.star",
    "go.star",
    "rust.star",
    "c.star",
    "zig.star",
    "swift.star",
    "kotlin.star",
    "elixir.star",
    "python.star",
    "ruby.star",
    "javascript.star",
]
