//! Rust implementation for `fabrik deps sync`.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use fabrik_core::{workspace_tool, workspace_tool_env};
use fabrik_frontend::DependencyEntry;
use serde::Deserialize;
use tokio::process::Command;

use super::deps::{entry_path, graph_output_path, SyncReport};
use super::vendor_graph::{
    write_graph_to, Ecosystem, ResolvedDependency, ResolvedGraph, ResolvedPackage, ResolvedSource,
};

#[derive(Deserialize)]
struct CargoMetadata {
    packages: Vec<MetadataPackage>,
    resolve: Option<MetadataResolve>,
    workspace_members: Vec<String>,
}

#[derive(Deserialize)]
struct MetadataPackage {
    name: String,
    version: String,
    id: String,
    manifest_path: String,
    source: Option<String>,
    targets: Vec<MetadataTarget>,
    #[serde(default)]
    build_dependencies: Vec<MetadataDependency>,
}

#[derive(Deserialize)]
struct MetadataTarget {
    #[allow(dead_code)]
    name: String,
    kind: Vec<String>,
    src_path: String,
    edition: String,
}

#[derive(Deserialize, Debug)]
struct MetadataDependency {
    #[allow(dead_code)]
    name: String,
}

#[derive(Deserialize)]
struct MetadataResolve {
    nodes: Vec<MetadataResolveNode>,
}

#[derive(Deserialize)]
struct MetadataResolveNode {
    id: String,
    deps: Vec<MetadataResolveDep>,
}

#[derive(Deserialize)]
struct MetadataResolveDep {
    name: String,
    pkg: String,
    dep_kinds: Vec<MetadataDepKind>,
}

#[derive(Deserialize)]
struct MetadataDepKind {
    #[serde(default)]
    kind: Option<String>,
}

pub(super) async fn sync(workspace: &Path, entry: &DependencyEntry) -> Result<SyncReport> {
    let metadata = run_cargo_metadata(workspace, entry).await?;
    let report = plan_vendor(&metadata)?;

    let vendor_dir = workspace.join("vendor").join(&entry.name);
    tokio::fs::create_dir_all(&vendor_dir)
        .await
        .with_context(|| format!("creating {}", vendor_dir.display()))?;
    let manifest = vendor_dir.join("fabrik.toml");
    tokio::fs::write(&manifest, &report.manifest_body)
        .await
        .with_context(|| format!("writing {}", manifest.display()))?;
    let lockfile = graph_output_path(workspace, entry, report.graph.ecosystem.lockfile_name());
    write_graph_to(&lockfile, &report.graph)
        .await
        .context("writing rust dependency graph")?;

    Ok(SyncReport {
        name: entry.name.clone(),
        ecosystem: entry.ecosystem,
        lockfile,
        manifest: Some(manifest),
        packages: report.graph.packages.len(),
        declared: Some(report.declared),
        skipped: Some(report.skipped),
        skipped_names: report.skipped_names,
    })
}

async fn run_cargo_metadata(workspace: &Path, entry: &DependencyEntry) -> Result<CargoMetadata> {
    let cargo = workspace_tool(workspace, "cargo")?;
    let manifest = entry_path(workspace, entry, &entry.manifest);
    let env = workspace_tool_env(
        workspace,
        &["cargo", "rustc"],
        &["CARGO_HOME", "RUSTUP_HOME", "RUSTUP_TOOLCHAIN"],
    )?;
    let output = Command::new(cargo)
        .args([
            "metadata",
            "--format-version",
            "1",
            "--locked",
            "--manifest-path",
        ])
        .arg(manifest)
        .env_clear()
        .envs(env)
        .current_dir(workspace)
        .output()
        .await
        .context("spawning cargo metadata")?;
    if !output.status.success() {
        return Err(anyhow!(
            "cargo metadata failed (exit {}): {}",
            output.status.code().unwrap_or(-1),
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    serde_json::from_slice(&output.stdout).context("parsing cargo metadata JSON")
}

struct VendorReport {
    manifest_body: String,
    graph: ResolvedGraph,
    declared: usize,
    skipped: usize,
    skipped_names: Vec<String>,
}

fn plan_vendor(metadata: &CargoMetadata) -> Result<VendorReport> {
    let pkg_by_id: BTreeMap<&String, &MetadataPackage> =
        metadata.packages.iter().map(|p| (&p.id, p)).collect();
    let workspace_ids: BTreeSet<&String> = metadata.workspace_members.iter().collect();

    let normal_deps = resolve_normal_deps(metadata);

    let mut body = String::new();
    body.push_str(
        "# Generated by `fabrik deps sync`. Edit at your peril; re-run the\n\
         # command instead. Source copying is not implemented yet, so\n\
         # declarations keep empty srcs placeholders.\n\
         #\n\
         # Crates with a build.rs (or that pull one through build-deps)\n\
         # are commented out; they need cargo.build_script wiring that is\n\
         # not yet plumbed end to end.\n\n",
    );

    let mut declared = 0usize;
    let mut skipped = 0usize;
    let mut skipped_names = Vec::new();

    let mut pkgs: Vec<&MetadataPackage> = metadata
        .packages
        .iter()
        .filter(|p| !workspace_ids.contains(&p.id))
        .filter(|p| {
            p.source
                .as_deref()
                .is_some_and(|s| s.starts_with("registry+"))
        })
        .collect();
    pkgs.sort_by(|a, b| a.name.cmp(&b.name).then(a.version.cmp(&b.version)));

    for pkg in pkgs {
        let Some(lib_target) = pick_lib_target(pkg) else {
            skipped += 1;
            skipped_names.push(format!("{}-{} (no library target)", pkg.name, pkg.version));
            continue;
        };
        let crate_name = sanitize_crate_name(&pkg.name);
        let manifest_dir = manifest_dir_of(pkg)?;
        let src_root = relative_to(&manifest_dir, &lib_target.src_path)
            .unwrap_or_else(|| lib_target.src_path.clone());
        let dep_lines = deps_for(pkg, &normal_deps, &pkg_by_id);
        let is_proc_macro = lib_target.kind.iter().any(|k| k == "proc-macro");
        let edition = &lib_target.edition;

        if manifest_has_build_script(pkg) {
            write_skipped(
                &mut body,
                pkg,
                &crate_name,
                edition,
                &src_root,
                is_proc_macro,
                &dep_lines,
            );
            skipped += 1;
            skipped_names.push(format!("{}-{} (build.rs)", pkg.name, pkg.version));
        } else {
            write_declared(
                &mut body,
                pkg,
                &crate_name,
                edition,
                &src_root,
                is_proc_macro,
                &dep_lines,
            );
            declared += 1;
        }
    }

    Ok(VendorReport {
        manifest_body: body,
        graph: resolved_graph_from_cargo(metadata),
        declared,
        skipped,
        skipped_names,
    })
}

fn resolved_graph_from_cargo(metadata: &CargoMetadata) -> ResolvedGraph {
    let deps_by_id = resolve_deps(metadata);
    let packages = metadata
        .packages
        .iter()
        .map(|pkg| {
            let version = Some(pkg.version.clone());
            let id = pkg.id.clone();
            let source = cargo_source(pkg);
            let dependencies = deps_by_id.get(&pkg.id).cloned().unwrap_or_default();
            let mut metadata = BTreeMap::new();
            metadata.insert(
                "cargo_package_id".to_string(),
                serde_json::Value::String(pkg.id.clone()),
            );
            metadata.insert(
                "manifest_path".to_string(),
                serde_json::Value::String(pkg.manifest_path.clone()),
            );
            ResolvedPackage {
                id,
                name: pkg.name.clone(),
                version,
                source,
                checksum: None,
                dependencies,
                metadata,
            }
        })
        .collect();
    ResolvedGraph::new(Ecosystem::Rust, packages)
}

fn cargo_source(pkg: &MetadataPackage) -> ResolvedSource {
    let Some(source) = pkg.source.as_deref() else {
        return manifest_dir_of(pkg).map_or(ResolvedSource::Unknown, |path| ResolvedSource::Path {
            path,
        });
    };
    if let Some(registry) = source.strip_prefix("registry+") {
        ResolvedSource::Registry {
            registry: Some(registry.to_string()),
        }
    } else if let Some(git) = source.strip_prefix("git+") {
        let (url, revision) = git
            .rsplit_once('#')
            .map_or((git.to_string(), None), |(url, revision)| {
                (url.to_string(), Some(revision.to_string()))
            });
        ResolvedSource::Git { url, revision }
    } else {
        ResolvedSource::Unknown
    }
}

fn resolve_deps(metadata: &CargoMetadata) -> BTreeMap<String, Vec<ResolvedDependency>> {
    let Some(resolve) = &metadata.resolve else {
        return BTreeMap::new();
    };
    resolve
        .nodes
        .iter()
        .map(|node| {
            let mut deps = BTreeSet::new();
            for dep in &node.deps {
                if dep.dep_kinds.is_empty() {
                    deps.insert(ResolvedDependency {
                        id: dep.pkg.clone(),
                        name: dep.name.clone(),
                        kind: "normal".to_string(),
                    });
                    continue;
                }
                for dep_kind in &dep.dep_kinds {
                    deps.insert(ResolvedDependency {
                        id: dep.pkg.clone(),
                        name: dep.name.clone(),
                        kind: dep_kind
                            .kind
                            .clone()
                            .unwrap_or_else(|| "normal".to_string()),
                    });
                }
            }
            (node.id.clone(), deps.into_iter().collect())
        })
        .collect()
}

fn resolve_normal_deps(metadata: &CargoMetadata) -> BTreeMap<String, Vec<String>> {
    let Some(resolve) = &metadata.resolve else {
        return BTreeMap::new();
    };
    resolve
        .nodes
        .iter()
        .map(|node| {
            let edges: Vec<String> = node
                .deps
                .iter()
                .filter(|d| d.dep_kinds.is_empty() || d.dep_kinds.iter().any(|k| k.kind.is_none()))
                .map(|d| {
                    let _ = &d.name;
                    d.pkg.clone()
                })
                .collect();
            (node.id.clone(), edges)
        })
        .collect()
}

fn deps_for(
    pkg: &MetadataPackage,
    normal_deps: &BTreeMap<String, Vec<String>>,
    pkg_by_id: &BTreeMap<&String, &MetadataPackage>,
) -> Vec<String> {
    let Some(edges) = normal_deps.get(&pkg.id) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for dep_id in edges {
        if let Some(d) = pkg_by_id.get(dep_id) {
            if d.source
                .as_deref()
                .is_some_and(|s| s.starts_with("registry+"))
            {
                out.push(d.name.clone());
            }
        }
    }
    out
}

fn write_declared(
    out: &mut String,
    pkg: &MetadataPackage,
    crate_name: &str,
    edition: &str,
    src_root: &str,
    is_proc_macro: bool,
    deps: &[String],
) {
    let _ = writeln!(
        out,
        "# {} {} ({})",
        pkg.name, pkg.version, pkg.manifest_path
    );
    if is_proc_macro {
        out.push_str("[[rust.proc_macro]]\n");
    } else {
        out.push_str("[[rust.library]]\n");
    }
    let _ = writeln!(out, "name = {:?}", pkg.name);
    let _ = writeln!(out, "crate_name = {crate_name:?}");
    let _ = writeln!(out, "edition = {edition:?}");
    let _ = writeln!(out, "crate_root = {src_root:?}");
    out.push_str("srcs = [] # add src_globs once sources are copied into vendor/\n");
    let _ = writeln!(out, "deps = {}", toml_array(deps));
    out.push('\n');
}

fn write_skipped(
    out: &mut String,
    pkg: &MetadataPackage,
    crate_name: &str,
    edition: &str,
    src_root: &str,
    is_proc_macro: bool,
    deps: &[String],
) {
    let _ = writeln!(
        out,
        "# {} {}: needs build.rs ({})",
        pkg.name, pkg.version, pkg.manifest_path
    );
    if is_proc_macro {
        out.push_str("# [[rust.proc_macro]]\n");
    } else {
        out.push_str("# [[rust.library]]\n");
    }
    let _ = writeln!(out, "# name = {:?}", pkg.name);
    let _ = writeln!(out, "# crate_name = {crate_name:?}");
    let _ = writeln!(out, "# edition = {edition:?}");
    let _ = writeln!(out, "# crate_root = {src_root:?}");
    out.push_str("# srcs = [] # populate after vendoring sources\n");
    let _ = writeln!(out, "# deps = {}", toml_array(deps));
    out.push('\n');
}

fn pick_lib_target(pkg: &MetadataPackage) -> Option<&MetadataTarget> {
    pkg.targets.iter().find(|t| {
        t.kind
            .iter()
            .any(|k| k == "lib" || k == "rlib" || k == "proc-macro")
    })
}

fn manifest_has_build_script(pkg: &MetadataPackage) -> bool {
    pkg.targets
        .iter()
        .any(|t| t.kind.iter().any(|k| k == "custom-build"))
        || !pkg.build_dependencies.is_empty()
}

fn manifest_dir_of(pkg: &MetadataPackage) -> Result<String> {
    let path = PathBuf::from(&pkg.manifest_path);
    path.parent()
        .ok_or_else(|| anyhow!("manifest path has no parent: {}", pkg.manifest_path))
        .map(|p| p.to_string_lossy().into_owned())
}

fn relative_to(base: &str, full: &str) -> Option<String> {
    let base = Path::new(base);
    let full = Path::new(full);
    full.strip_prefix(base)
        .ok()
        .map(|p| p.to_string_lossy().into_owned())
}

fn sanitize_crate_name(name: &str) -> String {
    name.replace('-', "_")
}

fn toml_array(values: &[String]) -> String {
    let mut out = String::from("[");
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        write!(out, "{value:?}").expect("writing to String cannot fail");
    }
    out.push(']');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rust_graph_dependency_ids_match_package_ids() {
        let dep_id = "registry+https://github.com/rust-lang/crates.io-index#dep@1.0.0";
        let app_id = "path+file:///repo#app@0.1.0";
        let metadata = CargoMetadata {
            packages: vec![
                package("app", "0.1.0", app_id, None),
                package(
                    "dep",
                    "1.0.0",
                    dep_id,
                    Some("registry+https://github.com/rust-lang/crates.io-index"),
                ),
            ],
            resolve: Some(MetadataResolve {
                nodes: vec![MetadataResolveNode {
                    id: app_id.to_string(),
                    deps: vec![MetadataResolveDep {
                        name: "dep".to_string(),
                        pkg: dep_id.to_string(),
                        dep_kinds: vec![MetadataDepKind { kind: None }],
                    }],
                }],
            }),
            workspace_members: vec![app_id.to_string()],
        };

        let graph = resolved_graph_from_cargo(&metadata);
        let app = graph
            .packages
            .iter()
            .find(|package| package.id == app_id)
            .unwrap();
        assert_eq!(app.dependencies[0].id, dep_id);
    }

    fn package(name: &str, version: &str, id: &str, source: Option<&str>) -> MetadataPackage {
        MetadataPackage {
            name: name.to_string(),
            version: version.to_string(),
            id: id.to_string(),
            manifest_path: format!("/repo/{name}/Cargo.toml"),
            source: source.map(str::to_string),
            targets: vec![MetadataTarget {
                name: name.to_string(),
                kind: vec!["lib".to_string()],
                src_path: format!("/repo/{name}/src/lib.rs"),
                edition: "2021".to_string(),
            }],
            build_dependencies: Vec::new(),
        }
    }
}
